name: NASA project CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js v18
        uses: actions/setup-node@v2
        with:
          node-version: '18'
      - run: npm i && npm run build --prefix client
  # deploy:
  # needs: build
